### PR TITLE
Feat/docker improvements

### PR DESCRIPTION
**Pull request by elreydetoda**
split from #25

### CODE REVIEW

**Comment by gerbrent** [comment]
Just looking for reviewers on this before merging..

**Review by ChanceM — APPROVED** [review]
I appreciate the addition of available variables, helps those of us that sometimes forget to RTFM.

**Review by ChanceM — APPROVED** [review]
LGTM more efficient and no need to copy the entire repo to the container.

**Comment by elreydetoda** [comment]
Based on @ChanceM's approval(s), I'm going to merge this.

**Pull request merged**
